### ISSUE TITLE
Links to pictures are broken.

### ISSUE THREAD

**Issue by jmccrary** [geany/plugins.geany.org#4]
I found that if I go to a specific page that contains a screenshot Google Chrome just showes a broken image link.  When I visit the actual direct link to the image, sourceforge gives a 404 error and I've quoted the whole message below.

_Note:_ this issue is only on geany-plugins domains, not `geany.org`.

When visiting `geany-plugins.sourceforge.net/set_filetype.png`

> An error has been encountered in accessing this page.
> 1. Server: geany-plugins.sourceforge.net
> 2. URL path: /set_filetype.png
> 3. Error notes: NONE
> 4. Error type: 404
> 5. Request method: GET
> 6. Request query string: NONE
> 7. Time: 2014-10-26 21:05:26 UTC (1414357526)
> 
> Reporting this problem: The problem you have encountered is with a project >web site hosted by SourceForge.net. This issue should be reported to the >SourceForge.net-hosted project (not to SourceForge.net).
> 
> If this is a severe or recurring/persistent problem, please do one of the >following, and provide the error text (numbered 1 through 7, above):
> 
> Contact the project via their designated support resources.
> Contact the project administrators of this project via email (see the upper right->hand corner of the Project Summary page for their usernames) at user->name@users.sourceforge.net
> If you are a maintainer of this web content, please refer to the Site >Documentation regarding web services for further assistance.
> 
> NOTE: As of 2008-10-23 directory index display has been disabled by default. >This option may be re-enabled by the project by placing a file with the name >".htaccess" with this line:
> 
> Options +Indexes

This is probably just a configuration issue in the website's sourceforge setup.  We talked about it in IRC a while ago but I figured it might get more coverage here.

**Comment by LarsGit223** [comment]
I checked the current situation and this is the result:

Plugin with image reference | Status
----------------------------------- | -------------
 **addons** | OK - Image is displayed 
 **automark** | OK - Image is displayed 
 **markdown** | OK - Images are displayed
 **debugger** | link to imageshack, no image displayed
 **geanyvc** | link to imageshack, no image displayed
 **autoclose** | dropbox - file not found
 **devhelp** | link to imageshack, no image displayed

I think it is not good to rely on external sites/services for storing the images. So I suggest the following as images stored on github work and it's a save service which is controlled by the maintainers of plugins.geany.org:
- change/extend the documentation in that way that plugin maintainers who want to include images in their documentation should make this available via a PR to plugins.geany.org and then reference the file on github
- remove the old not working image references
- close this as "won't fix" (if someone wants to re-new the pictures he can update the documentation and post a PR with the image)

**Comment by msphn** [comment]
I agree, anyway we shouldn't embed pictures from untrusted sources.

**Comment by dmaphy** [comment]
As the pull request is merged, I guess we can close this issue?

**Comment by LarsGit223** [comment]
Yes, we can't do anything about the images lost on imageshack/dropbox.
