### ISSUE TITLE
Explain how to install a plugin

### ISSUE THREAD

**Issue by dandv** [geany/plugins.geany.org#7]
First time Geany users. I search for "spellcheck plugin". Land at https://plugins.geany.org/spellcheck.html. How do I _install_ that plugin?

> After installed successfully, load the plugin in Geany's plugin manager

https://plugins.geany.org/ should explain how to install plugins, i.e. have a header "Installation" and link to https://plugins.geany.org/install.html.

**Comment by dmaphy** [comment]
As the HTML files for the plugins are generated, this has to be done by the plugin maintainer who maintains his README file for his plugin. If you wish to see this the maintainer probably appreciates an issue at the Geany Plugins project for his plugin here: https://github.com/geany/geany-plugins/issues.
