### ISSUE TITLE
Remove deleted plugins from the web

### ISSUE THREAD

**Issue by elextr** [geany/plugins.geany.org#8]
Geanygdb has been removed from geany-plugins but the web page for it still exists and is visible on the web so it shows up in things like google searches.

After they have been removed plugins should not show on the site to avoid confusion.

**Comment by LarsGit223** [comment]
Ping - little reminder. The file still seems to be on the web page.

**Comment by msphn** [comment]
We are excited to receive pull request 👍

**Comment by LarsGit223** [comment]
How? The plugin is not in the geany-plugins repository any more. Also please notice that the plugin is not listed under geany.plugins.org. But you can find the Geanygdb HTML page if you google it. Can it be that the HTML file is just a leftover on the webserver? The README doesn't exist any more I guess.

**Comment by msphn** [comment]
That could be, I have no access to the server. In this case maybe @dmaphy might have a clue.

**Comment by elextr** [comment]
> That could be, I have no access to the server. In this case maybe @dmaphy might have a clue.

Possibly, it appears at https://plugins.geany.org/geanygdb and of course Google can find it, so it shows in searches.

**Comment by eht16** [comment]
I deleted the geanygdb.html from the server manually. Without having studied the bunch of shell scripts here in deep, I assume it doesn't handle removed plugins at all.

While at it, I also updated the special handling of the renamed plugin (Geany)LaTeX in #11.

@frlan https://github.com/geany/geany-plugins/blob/master/latex/README contains to a broken link. You could update it to https://plugins.geany.org/latex/.

**Comment by Akronix** [comment]
I think the file [geanylatex.html](https://github.com/geany/plugins.geany.org/blob/master/content/geanylatex.html) can be deleted as well?

**Comment by Skif-off** [comment]
@Akronix , why? GeanyLatex has been renamed to Latex.

**Comment by Akronix** [comment]
hm, because [its html webpage](https://plugins.geany.org/latex.html) is being obtained by [the README in geany plugins](https://github.com/geany/geany-plugins/blob/master/latex/README)...or maybe I'm wrong?

**Comment by dmaphy** [comment]
There are some plugins not having a README file in the project, for those, we have the EXCLUDE_PLUGINS here to be able to maintain or own HTML file:

https://github.com/geany/plugins.geany.org/blob/master/gencontent.sh#L71

I've just removed the latex plugin from this exclude, as there is a README now (which is quite minimal, but hey, there is one!). @frlan you could update it to have a bit more content if you wish the website to display more then.

In the other points, @eht16 is right:

There is no automation to delete a plugin from the website until now and has to be done manually. Also, I think this will not be trivial to implement. As it doesn't happen that often that a plugin is deleted from the Geany plugins project, I think it will be fine if you open an issue and I will take care of this then.

Anyway, a pull request for automating this of course is always appreciated.

**Comment by Akronix** [comment]
Hmm so then geanylatex.html should not be in the repo anymore, right?

I have no idea how to do it automatically.

**Comment by dmaphy** [comment]
I've left over the geanylatex.html as @eht16 wrote it, containing a link to the proper place: https://plugins.geany.org/geanylatex.html
